// AUTOGENERATED FILE: rpcx server stub code
// compilable during generation.

package main

import (
  "flag"
  "time"

  metrics "github.com/rcrowley/go-metrics"
  "github.com/smallnest/rpcx/server"
  "github.com/smallnest/rpcx/serverplugin"
  "github.com/rpcx-ecosystem/rpcx-examples3/xgen"
)


var (
	addr     = flag.String("addr", "localhost:8972", "server address")
	basePath = flag.String("base", "/rpcx", "prefix path")
)
	
func main() {
	flag.Parse()

	_ = time.Second
	_ = metrics.UseNilMetrics
	_ = serverplugin.GetFunctionName

	s := server.NewServer()
	addRegistryPlugin(s)

	registerServices(s)

	s.Serve("tcp", *addr)
}
func registerServices(s *server.Server) {
	s.Register(new(xgen.Arith), "")
	s.Register(new(xgen.Echo), "")
	s.Register(new(xgen.TimeS), "")
}
func addRegistryPlugin(s *server.Server) {

		
}
